[pytest]
DJANGO_SETTINGS_MODULE = bookworm.settings
pythonpath = .
testpaths = libraries/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Reuse DB between test runs for speed (PostGIS creation is slow)
addopts = --reuse-db -v

# Markers
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')