# Generated by Django 6.0.1 on 2026-01-25 17:37

import cloudinary.models
import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text="Optional friendly name, e.g., 'The Oak Street Book Box'", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Accessibility notes, landmarks, special features')),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Geographic coordinates of the library', srid=4326)),
                ('submitted_by_email', models.EmailField(blank=True, help_text='Optional contact for admin follow-up (not publicly displayed)', max_length=254)),
                ('is_verified', models.BooleanField(db_index=True, default=False, help_text='Approved by admin for public display')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False for soft-deleted libraries (reported as non-existent)')),
                ('last_updated', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Auto-updated when a new Shelfie is added')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Libraries',
                'ordering': ['-last_updated'],
                'indexes': [models.Index(fields=['is_verified', 'is_active'], name='libraries_l_is_veri_1d9cca_idx'), models.Index(fields=['last_updated'], name='libraries_l_last_up_cb9e14_idx')],
            },
        ),
        migrations.CreateModel(
            name='IssueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('wrong_location', 'Wrong Location'), ('does_not_exist', "Doesn't Exist Anymore"), ('damaged', 'Damaged'), ('other', 'Other')], db_index=True, max_length=20)),
                ('description', models.TextField(blank=True, help_text='Additional details about the issue')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(db_index=True, default=False, help_text='Marked as resolved by admin')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_reports', to='libraries.library')),
            ],
            options={
                'verbose_name': 'Issue Report',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='Shelfie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('book_highlights', models.TextField(blank=True, help_text="Notable books spotted, e.g., 'Lots of kids books, some thrillers'")),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelfies', to='libraries.library')),
            ],
            options={
                'verbose_name': 'Shelfie',
                'verbose_name_plural': 'Shelfies',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
