# Generated by Django 6.0.1 on 2026-02-06 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuereport',
            name='shelfie',
            field=models.ForeignKey(blank=True, help_text='If reporting a specific photo, please link it here', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_reports', to='libraries.shelfie'),
        ),
        migrations.AlterField(
            model_name='issuereport',
            name='issue_type',
            field=models.CharField(choices=[('wrong_location', 'Wrong Location'), ('does_not_exist', "Doesn't Exist Anymore"), ('damaged', 'Damaged'), ('other', 'Other'), ('inappropriate_photo', 'Inappropriate Content'), ('wrong_library', "Photo Doesn't Match This Library"), ('blurry_unreadable', 'Blurry or Unreadable'), ('other_photo', 'Other Photo Issue')], db_index=True, max_length=20),
        ),
    ]
