# Generated by Django 6.0.1 on 2026-06-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0004_duplicate_candidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryWalkRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="We'll put this on your name tag.", max_length=120)),
                ('email', models.EmailField(help_text="Only used to reach you about this walk -- e.g. if heat or timing forces a change. We won't add you to any list.", max_length=254)),
                ('party_size', models.PositiveSmallIntegerField(default=1, help_text='Including you. A rough number is fine -- it helps us plan.')),
                ('favourite_book', models.CharField(blank=True, help_text='Optional. Goes on your name tag as a conversation starter.', max_length=120)),
                ('accessibility_notes', models.TextField(blank=True, help_text="Tell us about any accessibility needs and we'll reach out personally to make the day work for you.")),
                ('needs_accessibility_followup', models.BooleanField(default=False, help_text="I'd like someone to follow up with me about accessibility.")),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Library Walk registration',
                'verbose_name_plural': 'Library Walk registrations',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='stewardpartnership',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Steward Partnership', 'verbose_name_plural': 'Steward Partnerships'},
        ),
        migrations.RenameIndex(
            model_name='duplicatecandidate',
            new_name='libraries_d_disposi_fb0af8_idx',
            old_name='libraries_d_disposi_a3c2f1_idx',
        ),
        migrations.RenameIndex(
            model_name='scanevent',
            new_name='libraries_s_outcome_20dc83_idx',
            old_name='libraries_s_outcome_44c7b3_idx',
        ),
        migrations.RenameIndex(
            model_name='stewardpartnership',
            new_name='libraries_s_is_proc_0796a3_idx',
            old_name='libraries_s_is_proc_56b8a9_idx',
        ),
        migrations.AlterField(
            model_name='duplicatecandidate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='library',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated from name for SEO-friendly URLS', max_length=255),
        ),
        migrations.AlterField(
            model_name='scanevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stewardpartnership',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stewardpartnership',
            name='sticker_interest',
            field=models.BooleanField(default=False, help_text='Did the steward partner and ask for a Bookworm QR sticker on their library?'),
        ),
    ]
