# Generated by Django on 2026-09-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraries", "0005_librarywalkregistration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="library",
            name="stop_type",
            field=models.CharField(
                choices=[
                    ("standard", "Standard library"),
                    ("yarn", "Yarn library"),
                    ("art", "Art library"),
                    ("fridge", "Community fridge / pantry"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="standard",
                help_text="Kind of stop. Sets the map pin glyph; colour stays freshness.",
                max_length=16,
            ),
        ),
    ]
